<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use App\Traits\SetCreatedBy;

class AutogeneratedSystemPrice extends Model
{
    use HasFactory;
    protected $fillable = [
        'product_type_id',
        'percentage',
        'created_by',
        'updated_by'
    ];
}
