<?php

namespace Database\Factories;

use App\Models\AutogeneratedSystemPrice;
use Illuminate\Database\Eloquent\Factories\Factory;

class AutogeneratedSystemPriceFactory extends Factory
{
    protected $model = AutogeneratedSystemPrice::class;

    public function definition()
    {
        return [
            // Define model properties here
        ];
    }
}