<?php

namespace App\Http\Controllers\Products;

use App\Http\Controllers\Controller;
use App\Services\Products\AutogeneratedSystemPriceService\AutogeneratedSystemPriceService;
use App\Http\Requests\Products\AutogeneratedSystemPriceFormRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class AutogeneratedSystemPriceController extends Controller
{
    private $autogeneratedSystemPriceService;

    public function __construct(AutogeneratedSystemPriceService $autogeneratedSystemPriceService)
    {
        $this->autogeneratedSystemPriceService = $autogeneratedSystemPriceService;
    }

    public function index()
    {
        return $this->autogeneratedSystemPriceService->index();
    }

    public function show($id)
    {
        return $this->autogeneratedSystemPriceService->show($id);
    }

    public function store(AutogeneratedSystemPriceFormRequest $request)
    {
        // $request->validate([
        //     'percentage' => 'required|integer|between:1,100|unique:autogenerated_system_prices,percentage'
        // ]);
        if (\DB::table('autogenerated_system_prices')->exists()) {
            return response()->json([
                'errors' => [
                    'percentage' => ['A percentage has already been created.']
                ]
            ], 422);
        }

        // Validate the percentage input
        $request->validate([
            'percentage' => 'required|integer|between:1,100|unique:autogenerated_system_prices,percentage'
        ]);
        return $this->autogeneratedSystemPriceService->store($request->all());
    }

    public function update(AutogeneratedSystemPriceFormRequest $request, $id)
    {
        return $this->autogeneratedSystemPriceService->update($request->all(), $id);
    }

    public function destroy($id)
    {
        return $this->autogeneratedSystemPriceService->destroy($id);
    }
}
