<?php

namespace App\Http\Controllers;

use App\Models\AutogeneratedSystemPrice;
use Illuminate\Http\Request;

class AutogeneratedSystemPriceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(AutogeneratedSystemPrice $autogeneratedSystemPrice)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(AutogeneratedSystemPrice $autogeneratedSystemPrice)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, AutogeneratedSystemPrice $autogeneratedSystemPrice)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(AutogeneratedSystemPrice $autogeneratedSystemPrice)
    {
        //
    }
}
